spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://121.196.49.189:3310/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
